//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int CheckInID { get; set; }
        public int StudentID { get; set; }
        public string ShirtSize { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public string Notes { get; set; }
        public string CheckInBy { get; set; }
    }
}
