//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlatFile
    {
        public int ID { get; set; }
        public string TeacherAM { get; set; }
        public string TeacherPM { get; set; }
        public string Lang_Grade { get; set; }
        public string Student_FirstName { get; set; }
        public string Student_LastName { get; set; }
        public string Student_LastName_FirstName { get; set; }
        public string Student_FirstName_LastName { get; set; }
        public string Notes { get; set; }
    }
}
