//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shirt
    {
        public int ShirtsID { get; set; }
        public string ShirtPurpose { get; set; }
        public Nullable<int> YouthMedium { get; set; }
        public Nullable<int> YouthLarge { get; set; }
        public Nullable<int> Medium { get; set; }
        public Nullable<int> Large { get; set; }
        public Nullable<int> XL { get; set; }
    }
}
