//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentList
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ClassCode { get; set; }
        public string TeacherAM { get; set; }
        public string TeacherPM { get; set; }
        public string Notes { get; set; }
        public int StudentID { get; set; }
        public int CheckedIn { get; set; }
    }
}
